FROM nginx:1.25.3-alpine-slim
LABEL maintance="rlatjddmsrla@naver.com"

COPY ./index.html /usr/share/nginx/html/index.html
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
